### ISSUE TITLE
Missing opening <?php tag in .module after generating a content entity

### ISSUE THREAD

**Issue by weitzman** [Chi-teck/drupal-code-generator#101]
My guess is that I did not have a .module file before generating the entity so one was created but the generated code assumes a .module exists and has a `<?php` already.

DCG 2.6.2 on Drupal 9.4.8

**Comment by Chi-teck** [comment]
Tried with and without the module file. `<?php` was always in place.

**Comment by Chi-teck** [comment]
Cannot reproduce.
