### ISSUE TITLE
generate entity:content adds wrong permissions

### ISSUE THREAD

**Issue by superromeo** [Chi-teck/drupal-code-generator#102]
I create custom content type `rg_rfq_reaction` via `drush generate entity:content` and it created `permissions.yml` file with

> administer rg rfq reaction:
  title: 'Administer rg rfq reaction settings'
  restrict access: true
delete rg rfq reaction:
  title: Delete rg rfq reaction
...

Instead `rg rfq reaction` should be `rg_rfq_reaction`

**Comment by Chi-teck** [comment]
DCG version?

**Comment by superromeo** [comment]
No. 
Simple Drush 11.5.1.

**Comment by Chi-teck** [comment]
> Instead rg rfq reaction should be rg_rfq_reaction

You mean entity_type_id? That's actually debatable. Consider Block Content entity type in Drupal core.
The corresponding permission is named as [administer block content](https://git.drupalcode.org/project/drupal/-/blob/10.1.0-beta1/core/modules/block_content/block_content.permissions.yml#L13) (with spaces). Though I agree "administer rg rfq reaction" sounds weird.

**Comment by superromeo** [comment]
> You mean entity_type_id?

Yes.

Good point.

**Comment by Chi-teck** [comment]
The relevant core issue.
https://www.drupal.org/project/drupal/issues/2309869

**Comment by superromeo** [comment]
I think core issue is different.

Let's see, for instance, entity type `commerce_order_item` has permission `administer commerce_order_type`.

**Comment by Chi-teck** [comment]
> for instance, entity type commerce_order_item has permission administer commerce_order_type

Actually, it is [administer commerce_order](https://git.drupalcode.org/project/commerce/-/blob/8.x-2.36/modules/order/src/Entity/OrderItem.php#L39).

I am trying to figure out the best pattern for naming permissions. Drupal core follows this convention.
<dl>
  <dt>Entity with bundles</dt>
  <dd>administer {{ entity_type_name }} types</dd>
  <dt>Entity without bundles</dt>
  <dd>administer {{ entity_type_name }}</dd>
</dl>
Given that most of core entity types consist of a single word (typically module name) it's not clear whether the entity_type_name is a label or a machine name.

**Comment by Chi-teck** [comment]
Pushed a fix to 3.x branch. Given that this is more like an improvement than a bug I don't think it needs a backport to 2.x.

Leaving this issue open as this needs to be applied to config entity generator as well.

**Comment by superromeo** [comment]
I guess it is right solution.
Thank you, @Chi-teck!

**Comment by Chi-teck** [comment]
> this needs to be applied to config entity generator as well

Seems config entity generator already respects underscores. So nothing left to do here.
