### ISSUE TITLE
Allow to name provided answers instead of ordering them

### ISSUE THREAD

**Issue by DuaelFr** [Chi-teck/drupal-code-generator#107]
Hi and thank you for the great work you do here!

A while ago, we had to choose which generator to use for our custom needs and the only thing that prevented us to base our custom code on your work was that answer provided directly in the command line only rely on the order of questions. We think that it makes the usage of the generator commands less readable ans less maintainable. Plus, this does not allow to skip an answer if we need to.

We'd like to move from Drupal Console to Drupal Code Generator but our extensive use of this feature makes it hard to achieve.

For example, this is a command run by our CI/CD when building new environments:
```
vendor/bin/drupal combawa:generate-environment \
  --environment=dev \
  --environment-url=https://my-project.happyculture.coop \
  --dump-fetch-update \
  --dump-retrieval-tool cp \
  --fetch-source-path /home/jenkins/dumps/my_project.sql.gz \
  --reimport \
  --db-host=localhost \
  --db-port=3306 \
  --db-name=my_project \
  --db-user=db_user \
  --db-password='xxxxxxxxxxxxxx \
  --no-interaction
```

Do you think it would be possible to make this happen somehow? Maybe with a new `--answers` key that could take some JSON object.

**Comment by Chi-teck** [comment]
DCG used to accept answers as JSON.
https://github.com/Chi-teck/drupal-code-generator/blob/1.33.1/README.md?plain=1#L37

However, this was not convenient to encode values in command line. So I dropped this feature in DCG v2.

> Do you think it would be possible to make this happen somehow?

DCG generators are ordinary Symfony Console commands. So when implementing a custom generator you can define new options yourself same way as in Drupal Console. The only limitation is that it won't work with Drush as it limits available options. So you will need to register the generator in DCG app through event subscriber and call without Drush as follows.
```
./vendor/bin/dcg combawa:generate-environment
```
