### ISSUE TITLE
Bundle generation

### ISSUE THREAD

**Issue by AndyIRC** [Chi-teck/drupal-code-generator#11]
Hey. Thanks for this code, I am using it through Drush 9. I am migrating a site from D7 to D8 that uses the Entity Construction Kit (ECK). I'd love to not have to use ECK in D8. Given the progress in code generation with D8, like Drupal Console and your project, I think it might be feasible to get rid of it.

I was wondering if there is a way, or a plan, to be able to generate different bundles with the Content Entity generator? Using Drush I generated a fieldable entity, which is awesome, but I am going to need a chunk of bundles within that entity.

**Comment by Chi-teck** [comment]
Fixed in #12.
