### ISSUE TITLE
Parent QuestionHelper class is instantiated in some cases and causes a fatal error

### ISSUE THREAD

**Issue by nmangold** [Chi-teck/drupal-code-generator#112]
This error happens when trying to run `drush mi` or `drush migration`. I realize these are not proper aliases for the migration command, but this should fail gracefully, e.g. trying to run `drush migrate`.

`PHP Fatal error:  Uncaught TypeError: DrupalCodeGenerator\Style\GeneratorStyle::__construct(): Argument #3 ($question_helper) must be of type DrupalCodeGenerator\Helper\QuestionHelper, Symfony\Component\Console\Helper\QuestionHelper given, called in /var/www/html/vendor/chi-teck/drupal-code-generator/src/Command/Generator.php on line 106 and defined in /var/www/html/vendor/chi-teck/drupal-code-generator/src/Style/GeneratorStyle.php:39`

**Comment by Chi-teck** [comment]
I can not reproduce this.
Tested with Drupal 10.1 and Drush 12.

**Comment by nmangold** [comment]
The project I experienced this on uses Drush 11. I'll run tests on other projects to narrow down how to reproduce this.

**Comment by nmangold** [comment]
Drush 11 is the version experiencing this issue. Drush 12 does fail gracefully.

**Comment by Chi-teck** [comment]
Closing as Drush 11 [is not supported](https://www.drush.org/12.x/install/#drupal-compatibility) anymore.
