### ISSUE TITLE
Class naming convention

### ISSUE THREAD

**Issue by jurgenhaas** [Chi-teck/drupal-code-generator#124]
We're building code generators for some of our Drupal modules (e.g. ECA, DRD and others) and we just found out, that the class name needs to follow the *Generator name pattern.

Is that really necessary, or could that requirement be removed?

I mean, the classes are properly namespaced and come with all the PHP attributes to declare and make them discoverable. Enforcing the generator being part of the class name feels redundant, doesn't it?

**Comment by Chi-teck** [comment]
DCG itself does not force `Generator` suffix.  It might come from Drush generator discovery.

**Comment by jurgenhaas** [comment]
OK, I'll post a link to this issue in the Drush Slack channel to see if one of the experts over there can help. Thanks @Chi-teck

**Comment by jurgenhaas** [comment]
Sounds like has been introduced by drush due to discoverability. However, if we could use PHP to inspect for attributes on classes that have not been loaded, if they are autoloadable, then that could be removed.

Do you know if that's possible somehow?

**Comment by Chi-teck** [comment]
Yo'll have to implement own command discovery mechanism. That could be done through `GeneratorInfo` event.

```php
/**
 * {@selfdoc}
 */
final class GeneratorInfoSubscriber implements EventSubscriberInterface {

  /**
   * {@selfdoc}
   */
  public function onGeneratorDiscovery(GeneratorInfo $event): void {
    // @todo Implement generator auto-discovery here.
    $event->addGenerators(
      // Here we are registering just one command with known class name.
      // Use Drupal class loader service for dependency injection.
      new Example(),
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents(): array {
    return [GeneratorInfo::class => 'onGeneratorDiscovery'];
  }

}
```

For auto discovery you may use reflection like Drush 12 does or tagged services like Drush 11 did.

**Comment by jurgenhaas** [comment]
Yeah, it sounds like the drush maintainers don't seem to be keen to go for that, see the thread in slack where you also commented.

**Comment by Chi-teck** [comment]
Closing as there is nothing to do here.
