### ISSUE TITLE
Release for Symfony 7 compatibility

### ISSUE THREAD

**Issue by AlexSkrypnyk** [Chi-teck/drupal-code-generator#152]
Hi 👋  from https://github.com/drupal-composer/drupal-project

Could we please have a release for Symfony 7 compatibility as it has landed in April. This currently blocks `alpha`/`beta` level installs and requires to pin to commit
https://github.com/drupal-composer/drupal-project/pull/667

Thank you

**Comment by Chi-teck** [comment]
The work is in progress. See #151

**Comment by chesn0k** [comment]
Fixed in [4.0.0-alpha1](https://github.com/Chi-teck/drupal-code-generator/releases/tag/4.0.0-alpha1)

**Comment by AlexSkrypnyk** [comment]
@chesn0k
Thank you for releasing.

The alpha depends on `symfony/string` `7.1`, but Drupal core 11 uses `~7.0.7`.

Can the requirements for this package be lowered to use `~7.0`?

Otherwise - this cannot be used until `symfony/string` `7.1+` lands in core.


```
Problem 1
    - drupal/core-recommended 11.0.0-beta1 requires symfony/string ~v7.0.7 -> satisfiable by symfony/string[v7.0.7].
    - drupal/core-recommended 11.0.0-alpha1 requires symfony/string ~v7.0.4 -> satisfiable by symfony/string[v7.0.4, v7.0.7].
    - You can only install one version of a package, so only one of these can be installed: symfony/string[v5.1.0-BETA1, ..., v5.4.39, v6.0.0-BETA1, ..., v6.4.7, v7.0.0-BETA1, ..., v7.1.0-RC1].
    - chi-teck/drupal-code-generator 4.0.0-alpha1 requires symfony/string ^7.1 -> satisfiable by symfony/string[v7.1.0-BETA1, v7.1.0-RC1].
    - Root composer.json requires chi-teck/drupal-code-generator 4.0.0-alpha1 as 4.x-dev -> satisfiable by chi-teck/drupal-code-generator[4.0.0-alpha1].
    - Root composer.json requires drupal/core-recommended ^11@alpha -> satisfiable by drupal/core-recommended[11.0.0-alpha1, 11.0.0-beta1].

```

**Comment by chesn0k** [comment]
@AlexSkrypnyk Fixed it
