### ISSUE TITLE
plugin-manager generates Drush8 code

### ISSUE THREAD

**Issue by weitzman** [Chi-teck/drupal-code-generator#16]
Most people making new plugin managers will be using Drush9 by now.

**Comment by Chi-teck** [comment]
Maybe we don't need this Drush command at all. No other plugin managers have such a command. At some point Drush can provide a generic command to debug plugins like Drupal console does (`drupal debug:plugin <plugin_type>`).

**Comment by Chi-teck** [comment]
The drush command has been removed.
