### ISSUE TITLE
Release new version, to allow installing Drush in Drupal 11

### ISSUE THREAD

**Issue by gitressa** [Chi-teck/drupal-code-generator#177]
## Problem

You get an error if you try to install Drush in Drupal 11, which will be officially released late July 2024:

- https://github.com/drush-ops/drush/issues/6032.

## Solution

Drupal 11 is only a few weeks away, so all those who are installing Drupal 11 will run into this problem, and hit a full stop ...

Perhaps `chi-teck/drupal-code-generator` can get a release before too long, so that the users who are installing Drupal 11 don't get this error?

**Comment by gitressa** [comment]
This will also be an issue for those in the Drupal community who are working on getting contrib modules ready for Drupal 11.

**Comment by jcnventura** [comment]
+1

**Comment by Chi-teck** [comment]
DCG is currently in RC state. We plan to release stable version before Drupal 11.0 release.

**Comment by gitressa** [comment]
Thanks for replying @Chi-teck. The sooner it can be released, the better, since this is an issue for module maintainers getting ready for Drupal 11, and just generally, everyone who wants to run Drupal 11 ... Thanks!

**Comment by Chi-teck** [comment]
@gitressa this works for me
```
composer create drupal/recommended-project:^11@beta
cd recommended-project
composer require drush/drush
```

**Comment by gitressa** [comment]
You're right, great! I wonder why it works now ... maybe it was the release of [Drupal Code Generator 4.0.0-RC1](https://github.com/Chi-teck/drupal-code-generator/releases/tag/4.0.0-RC1)? Or do you think Drupal core constraints were relaxed, or something entirely different?

Anyway, thanks for a fast follow up, and for maintaining Drupal Code Generator!

**Comment by kopeboy** [comment]
It doesn't work with Drupal 11.0.0-rc1? 🤔

**EDIT**: I had to specifically require drush/drush:^13

**Comment by fk-devcode** [comment]
Trying to install Drupal 11 as a local development site running as docker container.
Stuck at:
$ ddev composer require drush/drush

ERROR: - drupal/core 11.0.0 requires php >=8.3.0 -> your php version (8.2.20) does not satisfy that requirement.

I tried specifying the version as I thought it might help

$ ddev composer require drush/drush:^13

but I'm also hitting a wall with this, cannot figure out a way to get it working. Not very experienced with DDEV or composer, so I'm not sure what to do.

**Comment by weitzman** [comment]
Edit you ~/.ddev/config.yaml to use php version 8.3 instead of 8.2

**Comment by fk-devcode** [comment]
> Edit you ~/.ddev/config.yaml to use php version 8.3 instead of 8.2

Hi... thanks for taking the time to reply. I don't see a config.yaml file in that directory, only global_config.yaml, which doesn't have directives for php, only for ports and other stuff. Do I have to add an 'environment variable' specific to PHP ?
