### ISSUE TITLE
Does it mistake or works as designed?

### ISSUE THREAD

**Issue by Niklan** [Chi-teck/drupal-code-generator#21]
It's a bit confusing: https://github.com/Chi-teck/drupal-code-generator/blob/master/templates/d8/module/content-entity/src/Entity/Example.php.twig#L148-L158

```php
  /**
   * {@inheritdoc}
   */
  public function isEnabled() {
    return (bool) $this->get('status')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setStatus($status) {
    $this->set('promote', $status);
    return $this;
}
```

Why is `setStatus()` change `promote` field? Does it correct? Because `isEnabled()` get status from `status` field. Maybe it's better to rename `setStatus()` to `setPromote()` in that way?

**Comment by Niklan** [comment]
In my case even `promote` field is not generated. So it's sets value to undefined field?

**Comment by Chi-teck** [comment]
It's a bug. The method obviously should set `status` rather than `promote` property.

**Comment by Chi-teck** [comment]
Fixed. Thanks.
