### ISSUE TITLE
Entity: The class prefix is based on the entity type label

### ISSUE THREAD

**Issue by defr** [Chi-teck/drupal-code-generator#28]
Right now, if you generate a new content entity, the class prefix is based on the camel-ization of the entity label. That means that if you have some special characters in your entity label, even if you fix it manually in the entity type id prompt, the class names will still be based on the label.

For example, if you create a module providing an content entity type with label "Føo Bår" and entity type id "foo_bar", instead of getting src/Entity/FooBar.php, you'll get src/Entity/FOBR.php

**Comment by Chi-teck** [comment]
Thanks.
