### ISSUE TITLE
Add ability to generate themes at destination modules/custom

### ISSUE THREAD

**Issue by rodrigoaguilera** [Chi-teck/drupal-code-generator#32]
I'm trying to write a generator like this

```
class SubthemeGenerator extends BaseGenerator
{
    protected $name = 'd8:theme-mytheme';
    protected $description = 'Generates a subtheme.';
    protected $alias = 'mytheme';
    protected $templatePath = __DIR__;
    protected $destination = 'themes/custom';

}
```

But seems like `$destination` is ignored and it generates the subtheme at the Drupal root.

Is it possible to define a custom destination path relative to the drupal root?

**Comment by Chi-teck** [comment]
Currently DCG by itself does not handle this option at all.
See notes here https://github.com/Chi-teck/drupal-code-generator/blob/master/src/Command/GeneratorInterface.php#L69

Drush only supports some predefined locations.
https://github.com/drush-ops/drush/blob/master/src/Commands/generate/Helper/InputHandler.php#L135

The workaround is defining destination in your command as a callback.
```
/**
 * {@inheritdoc}
 */
public function getDestination() {
  return function () {
    return 'themes/custom';
  };
}
```

**Comment by rodrigoaguilera** [comment]
That will do. Thanks.
Great project!
