### ISSUE TITLE
Latest tag missing from packagist

### ISSUE THREAD

**Issue by pazairfog** [Chi-teck/drupal-code-generator#33]
Tag 1.28.1 is missing from packagist.org : 
https://github.com/Chi-teck/drupal-code-generator/releases/tag/1.28.1
https://packagist.org/packages/chi-teck/drupal-code-generator

And since drush 9.6.1 : 
https://github.com/drush-ops/drush/commit/6f30e998e0d7e741baa686d9bee0fabbfc0a352f

When running `composer up drush/drush --with-all-dependencies` we are cloning dev-master version.
> Gathering patches for root package.
> Loading composer repositories with package information
> [...]
>   - Removing chi-teck/drupal-code-generator (1.28.0)
>   - Installing chi-teck/drupal-code-generator (dev-master 2e093f5): Cloning 2e093f5f95 from cache
>   - Updating drush/drush (9.6.0 => 9.6.1): Downloading (100%)

`composer show chi-teck/drupal-code-generator --all|grep versions`
> versions : dev-master, 1.x-dev, * 1.28.0, 1.27.0, 1.26.3, 1.26.2, 1.26.1, 1.26.0, 1.25.1, 1.25.0, 1.24.0, 1.23.2, 1.23.1, 1.23.0, 1.22.0, 1.21.3, 1.21.2, 1.21.1, 1.21.0, 1.20.0, 1.19.0, 1.18.4, 1.18.3, 1.18.2, 1.18.1, 1.18.0, 1.17.5, 1.17.4, 1.17.3, 1.17.2, 1.17.1, 1.17.0, 1.16.0, 1.15.1, 1.15.0, 1.14.0, 1.13.0, 1.12.1, 1.12.0, 1.11.0, 1.10.2, 1.10.1, 1.10.0, 1.9.1, 1.9.0, 1.8.1, 1.8.0, 1.7.0, 1.6.1, 1.6.0, 1.5.0, 1.4.1, 1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0

**Comment by Chi-teck** [comment]
Packagist has changed GitHub integration service.
> This package is using the legacy service integration that GitHub deprecated in January 2019 and will not auto-update anymore. Please set up the new GitHub Hook for Packagist so that it starts updating again.

I've just fixed the hook. The tag is published now. Thanks.
