### ISSUE TITLE
Cancel url used during submit() of a confirm form

### ISSUE THREAD

**Issue by weitzman** [Chi-teck/drupal-code-generator#36]
A bit confusing to use cancel url here IMO. https://github.com/Chi-teck/drupal-code-generator/blob/e3ce7b84f46f767ebb6405e5bfa8af3237f6ef89/templates/form/confirm/form.twig#L41

**Comment by Chi-teck** [comment]
It's quite common that submit URL is the same as cancel URL. So that many confirm forms in Drupal core use `getCancelUrl` in submit handler.
https://git.drupalcode.org/project/drupal/blob/8.7.7/core/lib/Drupal/Core/Entity/Form/DeleteMultipleForm.php#L294
I think that line was just copied from one of those forms.

**Comment by weitzman** [comment]
OK, that makes sense. Thanks.

**Comment by Chi-teck** [comment]
I actually think it makes sense to specify that URL explicitly. Thank you.

**Comment by andypost** [comment]
It is totally useless to redirect to `system.admin_config` by default, moreover it makes more work when used to generate confirm forms

**Comment by Chi-teck** [comment]
`system.admin_config` is just working placeholder. The correct destination depends on what actually the form confirms.

**Comment by andypost** [comment]
That's why I find it wrong - it's working, useless and hard to get that it requires to be edited before use, cancel URL less often needs editing

**Comment by Chi-teck** [comment]
Actually the cancel URL is the same.
https://github.com/Chi-teck/drupal-code-generator/commit/898984fe1bb1f22e0c4ababbee27b0cd04c07ab2#diff-bc9430a0adb47df7092fae160778f15aL32

> it requires to be edited before use

I think all generated code should be edited or at least reviewed before use.
