### ISSUE TITLE
Create .phpstorm.meta.php

### ISSUE THREAD

**Issue by batkor** [Chi-teck/drupal-code-generator#43]
Please create generator phpstorm meta file.
https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

###EXAMPLE
```
<?php

namespace PHPSTORM_META {

  use Drupal\node\NodeStorageInterface;

  override(\Drupal::service(0), map([
    'date.formatter' => \Drupal\Core\Datetime\DateFormatterInterface::class,
  ]));
  override(\Drupal::entityTypeManager()->getStorage(0), map([
    'node' => NodeStorageInterface::class,
  ]));
}
```

**Comment by Chi-teck** [comment]
There is a module that can generate this.
https://www.drupal.org/project/phpstorm_metadata

**Comment by Chi-teck** [comment]
I've added `phpstorm-metadata` generator. Thanks.

**Comment by weitzman** [comment]
Very much looking forward to this. Thanks.

**Comment by Chi-teck** [comment]
FYI, PhpStorm 2020.1 has just been released. It has improved support for [metadata](https://www.jetbrains.com/phpstorm/whatsnew/#metadata).
With proper metadata, it's capable to recognize magic properties.

![phpstorm-completion](https://user-images.githubusercontent.com/673139/79248780-b7607400-7e95-11ea-97cc-fbd8d92bec4a.png)

**Comment by weitzman** [comment]
Do you think its feasible to write metadata for all entity fields?

**Comment by Chi-teck** [comment]
Currently with provided metadata all fields of content entities are recognized as instances `FieldItemListInterface` which is quite good. Theoretically, it should be specify to more specific types for some properties but with the rules like this but for me it only works when the type of parent object is defined explicitly via `/** @var */` notation.
`override(\Drupal\node\Entity\Node::get(), map(['uid' => '\Drupal\Core\Field\EntityReferenceFieldItemList']));`
