### ISSUE TITLE
Entity administister permissions

### ISSUE THREAD

**Issue by Niklan** [Chi-teck/drupal-code-generator#44]
Currently, content entity generates this kind of permissions:

[Example](https://github.com/Chi-teck/drupal-code-generator/blob/master/templates/content-entity/src/Entity/Example.php.twig#L70):

```twig
…
{% if bundle %}
 *   admin_permission = "administer {{ entity_type_label|lower }} types",
{% elseif fieldable %}
 *   admin_permission = "administer {{ entity_type_label|lower }}",
{% else %}
…
```

Is that safe and works as intended or this is a bug?

If user tries to generate custom entity and gives it label "Node" it will share permissions with core "node" module. This is not very obvious and can lead to a lot of problems in the future.

Config entity type on the other hand, [uses](https://github.com/Chi-teck/drupal-code-generator/blob/master/templates/configuration-entity/src/Entity/Example.php.twig#L32) `entity_type_id`.

I propose to change content entity type permission from using this `{{ entity_type_label|lower }}` to that `{{ entity_type_label }}`. This will make generation across entity types consistent and safer for common entity labels.

**Comment by Chi-teck** [comment]
> I propose to change content entity type permission from using this {{ entity_type_label|lower }} to that {{ entity_type_label }}.

I didn't quite get the difference. Permissions are supposed to be in lower case.

**Comment by Niklan** [comment]
Mistaken, sorry. The variable must be `{{ entity_type_id }}`

**Comment by Chi-teck** [comment]
`{{ entity_type_id }}` is machine name. In Drupal core permissions are typically  written as lower-cased  human names.

**Comment by Chi-teck** [comment]
Consider [image style](https://github.com/drupal/drupal/blob/9.0.0-beta2/core/modules/image/src/Entity/ImageStyle.php) entity type.

**ID:** image_style
**Label:**  Image style
**Permission:** administer image styles

In this case the permission appears as lower-cased entity label in plural form.

**Comment by Niklan** [comment]
But if we use:

- **ID**: `my_custom_node`
- **Label**: `Node`

We get **permission** `administer node` and `access node overview` (not sure why it isn't in plural form) but it can conflict with core node module permissions. Also, this can lead for this type of problem in other cases when label is different from entity type ID and can conflict with other modules.

**Comment by Niklan** [comment]
For reference, commerce uses the entity type ID in their permissions:

- https://git.drupalcode.org/project/commerce/-/blob/8.x-2.x/modules/product/commerce_product.permissions.yml#L1
- https://git.drupalcode.org/project/commerce/-/blob/8.x-2.x/modules/order/commerce_order.permissions.yml#L1

Core has a lot of modules with very common names. In this situation this can make problems that not obvious at the moment of entity generation. Another example. The Tour module can conflict with Tour (vacation) entities. But this is just a label, not an ID. In other words, current implementation can mess up "namespaces" for permissions.

**Comment by Chi-teck** [comment]
Well, I think that's not a good idea to label your custom entity type as "Node". 

> commerce uses the entity type ID
That are not entity type IDs, because it contains spaces not underscores.

**Comment by Chi-teck** [comment]
Technically permission names are neither human names nor machine names. They are something in between.
I think the permission should be something like this  "administer {{ entity_type_id|replace('_', ' ' }}"

**Comment by Niklan** [comment]
Node is just an example and this is actually is not good name for custom entity. But "Tour" is not a bad label for the custom entity and it conflicts with Tour module which doesn't have an entity type, but there is possibility for permissions intersections in this case.

In theory this can lead to access violations for custom entities.

> They are not entity type IDs, because they contain spaces not underscores.

We can also reference to `\Drupal\entity\EntityPermissionProvider` which provides permissions with entity type ID as well:

```php
…
    $permissions["view {$entity_type_id}"] = [
      'title' => $this->t('View @type', [
        '@type' => $plural_label,
      ]),
    ];
…
```

> I think the permission should be something like this "administer {{ entity_type_id|replace('_', ' ' }}"
Yes, it's simply much safer. Who needs more shorten name can easily edit it and think for yourself in that case.
