### ISSUE TITLE
Feature request: Plugin generator for content entity type

### ISSUE THREAD

**Issue by wizonesolutions** [Chi-teck/drupal-code-generator#45]
Right now, DCG can only generate modules for a content entity. But existing modules might want to add a new content entity type. Is it possible to create a template for that? Where would I copy/move the existing files from the module version? Maybe I can send a PR.

(The idea is for this to make it into Drush, which I believe uses this project anyway.)

**Comment by Chi-teck** [comment]
That's already implemented in DCG 2. I think it'll take a lot of effort to backport this to DCG 1.
