### ISSUE TITLE
Rationale of this project?

### ISSUE THREAD

**Issue by miloskroulik** [Chi-teck/drupal-code-generator#5]
I'm kind of confused, because I thought, that generating boilerplate code is a [Drupal Console](https://drupalconsole.com/) task now. Why should I use this project, instead of DC? Is there some sort of feature comparison anywhere?

**Comment by Chi-teck** [comment]
I don't think there is a feature comparison somewhere.  At the moment I can name the following key features of this project.

1. DCG focused only on code generation.
2. DCG does not require Drupal installation to generate code.
3. DCG supports Drupal 7.

This project was started a long time ago when Drupal Console was not well known yet. See [this ticket](https://github.com/hechoendrupal/drupal-console/issues/275) for details.

**Comment by miloskroulik** [comment]
That makes sense. Thanks a lot.
