### ISSUE TITLE
Replace or improve Drupal versions mentions

### ISSUE THREAD

**Issue by Niklan** [Chi-teck/drupal-code-generator#50]
Since there is already Drupal 9, some things can be confusing.

I suggest replacing mentioning "Drupal 8" with "Drupal" or "Drupal 8+", depends on preference and context.

The project has 17 occurrences for "Drupal 8" for now:

![image](https://user-images.githubusercontent.com/2356744/88358589-f5b8d980-cd88-11ea-8f39-774764018ca4.png)

For example [/templates/module-file/module.twig](https://github.com/Chi-teck/drupal-code-generator/blob/master/templates/module-file/module.twig#L8) has comment "This file is no longer required in Drupal 8.". This can be improved like so "This file is no longer required in Drupal 8+.", "This file is no longer required in Drupal." or "This file is no longer required since Drupal 8.". Since there is the link for the change record explains this, I don't think version is needs to be mentioned.

For reference, we can use Drupal Core convention — [Drupal is mentioned without major version](https://www.drupal.org/node/3134676).

I want to discuss this before doing any changes.

**Comment by Chi-teck** [comment]
I most cases we simply remove the reference to 'Drupal 8'
For example, "Generates Drupal 8 module" can become "Generates a module".

As of "This file is no longer required in Drupal 8." I propose removing this comment at all.
