### ISSUE TITLE
Display version when running dcg --version when using version 1.x

### ISSUE THREAD

**Issue by miloskroulik** [Chi-teck/drupal-code-generator#56]
I ran `dcg --version` command to see the version number, but the output was `Drupal Code Generator`.

**Comment by Chi-teck** [comment]
That has been fixed in DCG 2.
https://github.com/Chi-teck/drupal-code-generator/blob/master/src/Application.php#L51

**Comment by miloskroulik** [comment]
Thanks. Unfortunately, I can't use it, because I need a D8 support.

**Comment by Chi-teck** [comment]
DCG 1 is not supported any more.
