### ISSUE TITLE
Template for d8 migrate source generates incorrect code

### ISSUE THREAD

**Issue by Eli-TW** [Chi-teck/drupal-code-generator#57]
Observed in 1.32.1, but 1.32.5 still has this issue.

Template for d8 migrate source includes the following function:
```
  public function getIds() {
    $ids['id']['type'] = [
      'type' => 'integer',
      'unsigned' => TRUE,
      'size' => 'big',
    ];
    return $ids;
  }
```
This should be 

```
  public function getIds() {
    $ids['id'] = [
      'type' => 'integer',
      'unsigned' => TRUE,
      'size' => 'big',
    ];
    return $ids;
  }
```

Building a source using with type/unsigned/size under the additional type key causes the error message

 [error]  Migration failed with source plugin exception: The &quot;&quot; plugin does not exist. Valid plugin IDs for Drupal\Core\Field\FieldTypePluginManager are: block_field, datetime, daterange, entity_reference_revisions, file_uri, file, image, link, metatag, list_float, list_string, list_integer, path, redirect_source, text_with_summary, text, text_long, video_embed_field, viewsreference, integer, uri, entity_reference, uuid, float, email, timestamp, string, language, created, changed, map, string_long, password, decimal, boolean

to be triggered on running migrate:import

PR to follow.

**Comment by Chi-teck** [comment]
Fixed. Thanks for the report.
