### ISSUE TITLE
can't cd to /var/www/dcg: No such file or directory

### ISSUE THREAD

**Issue by Niklan** [Chi-teck/drupal-code-generator#61]
While working on #59, I run `./scripts/run-sut-tests.sh`

This script makes the assumption of where DCG is located.

https://github.com/Chi-teck/drupal-code-generator/blob/0a16f4cca86d5d62167163d641e6ec77e822038e/scripts/run-sut-tests.sh#L10

So, my run ends up with error:

```
./scripts/run-sut-tests.sh: cd: line 10: can't cd to /var/www/dcg: No such file or directory
```

Looks like it's called at the very end, so this is not a big deal. But why it's even called? Looks like it doesn't do anything and removing this line doesn't change anything.

**Comment by Chi-teck** [comment]
That needs to be replaced with proper DCG path.

**Comment by Niklan** [comment]
@Chi-teck do you mean this one: `$DEFAULT_DCG`? But this variable defined after the function, is this will works?
