### ISSUE TITLE
1.x: Ensure that the default answer is normalized

### ISSUE THREAD

**Issue by codebymikey** [Chi-teck/drupal-code-generator#66]
When the `answer` option is specified and running in non-interactive mode, the default answer retrieved in the [InputHandler](https://github.com/Chi-teck/drupal-code-generator/blob/801e580/src/Helper/InputHandler.php#L109-L115)

Sometimes needs to be normalized like this: https://github.com/symfony/console/blob/cbb6922/Helper/QuestionHelper.php#L146-L148

Using the `update_helper` module and running the following:
```
drush generate configuration-update --answers='{"module":"my_module"}'
```

Where the [`include-modules`](https://git.drupalcode.org/project/update_helper/-/blob/6288e3aa/src/Generators/ConfigurationUpdate.php#L128-130) option is omitted so that the default value is used and normalized from a string to an array, however, that doesn't appear to be the case.
So it leads to a crash because the [value is a string rather than an array](https://git.drupalcode.org/project/update_helper/-/blob/6288e3aa/src/Generators/ConfigurationUpdate.php#L156).

Perhaps it should have an additional check for if it's a string before attempting to normalize to avoid accidentally normalizing an already normalized default answer:

```php
if ($normalizer = $question->getNormalizer()) {
  if (is_string($answer)) {
    // Normalize from string to the appropriate format.
    $answer = $normalizer($answer);
  }
}
```

**Comment by Chi-teck** [comment]
That makes sense. FYI in DCG 2 answers are always passed as strings.
