### ISSUE TITLE
[1.x]  Running commands from other commands, `HelperSet` is initialised at Application level, so InputHandler is filled with questions from prior commands.

### ISSUE THREAD

**Issue by richardgaunt** [Chi-teck/drupal-code-generator#67]
This affects running multiple commands from one

Running commands from other commands, `HelperSet` is initialised at Application level, so InputHandler is filled with questions from prior commands.

I have a generator that:

- reads in csv data
- calls another command to generate entity types with that data (repeatedly)
 
The input from the last command is still present because the `InputHandler` is not re-initialised each command only at application level.

Potential solutions:
- Initialise a command initiated `HelperSet` instead of at Application
- Re-initialise `InputHandler` within the command so it is clean when the command is run.

Happy to implement a solution, would either of the above solutions be preferred or accepted?

**Comment by Chi-teck** [comment]
That needs more details or better a reference to code that implements two commands.

**Comment by richardgaunt** [comment]
Thank you for the speedy reply.

Here is an example implementation - note how it's a command calling other command's within the structure.

The problem is the `HelperSet` is initialised in `Application` and `InputHandler` stores the questions already asked questions on a property `questions` because it is only initialised once, commands called within commands and then when we call the same command several times like iterating through a csv, the questions have already been asked according to the InputHandler and so the $vars are the same as the first time we called that command.

```
<?php


use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;

class CustomGenerator extends \DrupalCodeGenerator\Command\BaseGenerator {

  /**
   * {@inheritdoc}
   */
  protected function interact(InputInterface $input, OutputInterface $output) {
    parent::initialize($input, $output); // TODO: Change the autogenerated stub
    $rows = $this->getRowFromCSV();
    foreach ($rows as $row) {
      $cmd = $this->getCommandNameFromRow($row);
      /** @var \Symfony\Component\Console\Command\Command $command */
      $command = $this->getApplication()->find($cmd);
      $sub_input = new ArrayInput([
        '--answers' => json_encode($this->getCommandArguments($cmd, $row))
      ]);
      $sub_output = new ConsoleOutput();
      $command->initialize($sub_input, $sub_output);
      $return_code = $command->run($sub_input, $sub_output);
    }
  }

}
```

**Comment by Chi-teck** [comment]
Helper is set on Application level same way as in Symfony Console. I could think of two options.
1. Replace the helper set with new instance in the loop. Something like this `$this->getHelperSet()->set(new Helper())`.
2. Initialize a new DCG application for the second command. That's how `drush generate` embed DCG.
https://github.com/drush-ops/drush/blob/10.6.0/src/Commands/generate/GenerateCommands.php#L58

**Comment by richardgaunt** [comment]
I've done your first suggestion to overcome in my application and agree that's the way Symfony sets helpers, so I guess what I am saying is:

It just seems to be a problem that `InputHandler` holds state between commands and it's not an obvious problem until you have done what I've done.

Maybe InputHandler should initialise on each command as you suggest in point 1? I'm happy to create a patch if you agree?

**Comment by Chi-teck** [comment]
Ideally, the Input handler should not have state at all. That could be achived if we pass `askedQuestions` as a parameter to the `collectVars()` method. Unfortunetly that would make the caller code a way more verbose. Initialization the handler on each command will work just for your case. That might not be desirable for other cases. For example someone may want to run second command that shares `answers` option with the first one. So that I think the `inputHandler` should be instantiated consciously when needed.

**Comment by richardgaunt** [comment]
That's a fair design decision.
Thanks for your work with the library, it's an amazing collection.
