### ISSUE TITLE
how to use default values via --answers options

### ISSUE THREAD

**Issue by richardbporter** [Chi-teck/drupal-code-generator#7]
When providing answers via the `--answers` option, is it possible to allow the default values to be used non-interactively?

For example, `dcg twig-extension -a '{"name": "Example", "machine_name": "example", "class": "ExampleTwigExtension"}'` Leaving off `class` prompts for input. Other values like `true`, `false` and `null` don't seem to work either.

Thanks!

**Comment by Chi-teck** [comment]
That's not clear to me. Do you still have to input `class` when running the above command?

**Comment by richardbporter** [comment]
If you run the following command:
`dcg twig-extension -a '{"name": "Example", "machine_name": "example"}'`

You are prompted to enter the Class name. I'm just wondering if there is some way to avoid that prompt and use the default value.

**Comment by Chi-teck** [comment]
No, it is not possible. To avoid prompt you should provide "class" value explicitly.
`dcg twig-extension -a '{"name": "Example", "machine_name": "example", "class": "ExampleTwigExtension"}'`

**Comment by Chi-teck** [comment]
> Other values like true, false and null don't seem to work either.

Boolean values work for me when passed as is (`true` or `false`).

**Comment by richardbporter** [comment]
True, but it uses the boolean value as the class name. Not a huge deal but it would be great if omitted values would use the default value provided in the generator. 

I haven't dug into the code yet but do you think there is a way of accomplishing this? Would you consider a PR for this feature?

**Comment by Chi-teck** [comment]
> it uses the boolean value as the class name

Right now if I omit the `class` answer or pass `null` as its value it prompts for input. Does it work the same way for you? How can I reproduce the issue with boolean value as the class name?

**Comment by Chi-teck** [comment]
It should be possible now to pass null value to indicate that the question should accept its default value.
`dcg twig-extension -a '{"name": "Example", "machine_name": "example", "class": null}'`
In case you are doing some scripting, I would not recommend relying on this feature because the default values may change over time.

I also added support for string confirmation answers (yes/no).

**Comment by richardbporter** [comment]
Nice! Just tested it out and it works as expected.

Yes, I have created some custom generators (with Drush) that are determining some more complicated default answers. This is much more convenient than having to pass those in on the CLI.

Thanks very much!
