### ISSUE TITLE
entity-bundle-class suggestions

### ISSUE THREAD

**Issue by weitzman** [Chi-teck/drupal-code-generator#71]
1. Add an `All` option so that user can generate all bundles for an entity type at once. Also, allow multi-select. These are especially important if we keep writing alter hook implementations. That would be tedious to clean up.
2. The question text "Would you like to generate a base class?" is problematic. What if I want my bundle class to use an existing base class? Perhaps reword to 'Use a base class?'. That way it doesn't feel like you are overwriting an existing base class, which would be bad.

**Comment by Chi-teck** [comment]
> Perhaps reword to 'Use a base class?'.

Done.

**Comment by Chi-teck** [comment]
Most of entity types have just one or two bundles. So having `ALL` option seems redundant. I just set the bundle choice to multi-select  so it should not  be a big deal to select all bundles using comma as separator.

<details><summary>Output</summary>
<p>

```
$ /var/www/d9/docroot/vendor/bin/dcg entity-bundle-class

 Welcome to entity-bundle-class generator!
–––––––––––––––––––––––––––––––––––––––––––

 Module machine name [docroot]:
 ➤ bar

 Entity type:
  [ 1] Custom block
  [ 2] Comment
  [ 3] Contact message
  [ 4] File
  [ 5] Custom menu link
  [ 6] Content
  [ 7] URL alias
  [ 8] Shortcut link
  [ 9] Taxonomy term
  [10] User
 ➤ 6

 Bundles, comma separated:
  [1] Article
  [2] Basic page
 ➤ 1, 2

 Class for Article bundle [ArticleBundle]:
 ➤ 

 Class for Basic page bundle [PageBundle]:
 ➤ 

 Use a base class? [No]:
 ➤ 

 The following directories and files have been created or updated:
–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
 • bar.module
 • src/Entity/Bundle/ArticleBundle.php
 • src/Entity/Bundle/PageBundle.php

```
</p>
</details>
