### ISSUE TITLE
core: 8.x in model.info.yml

### ISSUE THREAD

**Issue by PetersRicardo** [Chi-teck/drupal-code-generator#72]
Hi there,

in the model.info.yml ([templates/module/model.info.yml.twig](https://github.com/Chi-teck/drupal-code-generator/blob/master/templates/module/model.info.yml.twig))  used for generating a module info yml, there is still a reference to `core: 8.x`
I think with D8 being end of live removing this line would be enough and it doesn't need to be configurable.
Do you agree? 
If you want it to be configurable, I could set up a pull request.

**Comment by Chi-teck** [comment]
That makes sense.

**Comment by PetersRicardo** [comment]
I've created a pull request:
#73

**Comment by Chi-teck** [comment]
That has been fixed in #73.
