### ISSUE TITLE
Drop support for global installation

### ISSUE THREAD

**Issue by Chi-teck** [Chi-teck/drupal-code-generator#76]
That applies to both Composer and PHAR installation.

## Reasons

1. It seems global installation is not widely used. Most people have DCG installed as a local Composer package and use it through Drush.
2. Maintenance cost. No need to dump services and hooks for autocompletion. Also PHAR compiler can be removed.
3. Reducing complexity. Currently generators follow "Progressive Enhancement" strategy. Meaning they are capable to work when Drupal is not bootstrapped. And if Drupal context is availble they can enhance user experience somehow. For instance by providing more accurate autocompletion. In practice that looks like follows.

    ```php
    if ($this->drupalContext) {
      // Some code that enhances UX if Drupal is installed.
    }
    ```
    This duality brings complexity. With this change we can get rid of this condition and assume that Drupal Context is always available. Eventually that would allow generators to implement deeper integration with Drupal.
    
## Proposed solution
- [x] Update installation instruction in README.md and stop generating PHAR file since 2.4.0.
- [x] Remove Drupal Conext conditions, dumper scripts, PHAR complier, etc.
- [x] Require Drupal core for testing.

**Comment by weitzman** [comment]
👍  Makes sense to me.

**Comment by Chi-teck** [comment]
Fixed in 3.x branch.
