### ISSUE TITLE
Class name validator

### ISSUE THREAD

**Issue by miromichalicka** [Chi-teck/drupal-code-generator#8]
Hi,
is there any reason why in validateClassName method you require on the second place only 0 from numbers? Referenced doc says nothing about that.

**Comment by Chi-teck** [comment]
That's a bug.

**Comment by miromichalicka** [comment]
Would the correct solution be rollback to regexp from php documentation? I can open PR with that.

**Comment by Chi-teck** [comment]
PHP [allows](http://php.net/manual/en/language.variables.basics.php) underscores and Unicode characters in class names. I did not find rules about this in [Drupal coding standards](https://www.drupal.org/docs/develop/coding-standards/object-oriented-code#naming) but Drupal core classes do not use them.
So the regexp could something like this `/^[A-Z][a-zA-Z0-9]+$/`.
