### ISSUE TITLE
Remove asset-packagist as a repo source

### ISSUE THREAD

**Issue by jameswilson** [Chi-teck/drupal-code-generator#84]
Asset Packagist has failed to renew its domain, with a "Renew" link that points to a Russian registrar. 

There are well documented workarounds to help projects move away from asset-packagist, eg 
https://ryanszrama.com/blog/04-18-2022/replace-asset-packagist-custom-package-repositories

For more details, see thread on Drupal community slack's #contribute channel: https://drupal.slack.com/archives/C1BMUQ9U6/p1650304302016749

Suggested approach, remove mention of asset packagist from codebase.

I found these mentions in code:

```
src/Command/Drupal_8/Project.php:108:    $questions['asset_packagist'] = new ConfirmationQuestion('Would you like to add asset-packagist repository?', FALSE);
src/Command/Drupal_8/Project.php:217:        'url' => 'https://asset-packagist.org',
```

**Comment by Chi-teck** [comment]
Seems that domain up now. Anyway, I am thinking of dropping the command `project` as it has quite a big maintaince cost and seems not to be widely used.

**Comment by Chi-teck** [comment]
Project generator has been removed in 3.x branch.
