### ISSUE TITLE
Add Revision UI while generating a content entity

### ISSUE THREAD

**Issue by bhanu951** [Chi-teck/drupal-code-generator#92]
As per the Issue [#2350939](https://www.drupal.org/project/drupal/issues/2350939) on Drupal.org we can have Revision UI for Revisionable Entities. 

Update Content Entity Generator class to include Revision UI annotations in Entity Class . 

The [CR](https://www.drupal.org/node/3160443) has additional details for the syntaxes

Edit:

We might need to consider the changes that might be introduced in the issue [#2976861](https://www.drupal.org/project/drupal/issues/2976861) as well. Thanks.

**Comment by Chi-teck** [comment]
Related #39.

The revision UI for custom entities will be available in Drupal ~~8.1~~ 10.1. I wonder if we can support it without breaking compatibility with Drupal ~~8.0~~ 10.0.

**Comment by greggles** [comment]
I'm surprised this module is supporting Drupal 8.0? Drupal 8 (especially 8.0) is pretty far past end of life.

**Comment by Chi-teck** [comment]
Sorry, I misspelled versions in the previous comment.
DCG 3 supports only Drupal 10.

**Comment by greggles** [comment]
OK, got it. [Looks like](https://www.drupal.org/about/core/policies/core-release-cycles/schedule) Drupal 10.0 will be with us until December 13, 2023 (UTC) so I agree it's good to support that :) 

Thanks!

**Comment by Chi-teck** [comment]
Fixed in #128.
