### ISSUE TITLE
Create command for generate post_update file

### ISSUE THREAD

**Issue by batkor** [Chi-teck/drupal-code-generator#94]
Add command for generate `*.post_update.php`

Default contains on file
```
<?php

/**
 * @file
 * Post update functions for "module_name" module.
 */
```

**Comment by Chi-teck** [comment]
It can be created through `drush generate hook` command.

Note that there is a bug #93 that has been fixed but not released yet.

**Comment by batkor** [comment]
Thanks. Nice
