### ISSUE TITLE
Add "drush generate readme" command

### ISSUE THREAD

**Issue by JPustkuchen** [Chi-teck/drupal-code-generator#99]
From: https://github.com/drush-ops/drush/issues/5554

I really enjoy using the drush generate command for all sorts of things, as it saves a lot of time, when creating a module. And I recently wondered why there is no drush generate readme command, which would generate a [README.md template](https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/documenting-your-project/readmemd-template), using Drupal's README.md template.

**Describe the solution you'd like**
Implement a drush generate readme command to easily generate a module's README.md.

**Comment by Chi-teck** [comment]
Added a generator for README.md to 3.x branch.
https://github.com/Chi-teck/drupal-code-generator/tree/3.x/templates/_readme

Thank you.

**Comment by JPustkuchen** [comment]
Thank you very very much @Chi-teck! Super cool :)

**Comment by gitressa** [comment]
This is awesome, thanks!
